# ~/.config/starship.toml

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = "ğŸ¤™"

[git_branch]
symbol = "ï˜ "

[python]
symbol = "ï Ÿ "
python_binary = "python3"

[nodejs]
format = "using [$symbol$version]($style) "

[package]
format = "[$symbol$version]($style) "
symbol = "ï’‡ "